### ISSUE TITLE
Weird border on some Search inputs

### ISSUE THREAD

**Issue by justinkluever** [physgunco/roadmap#39]
There are weird borders arround some inputs (only saw it on search inputs tho)
![image](https://user-images.githubusercontent.com/19864478/133855817-b1bdc345-6fc3-48a6-ac77-859a17759efb.png)

found on:
https://physgun.com/dashboard/purchases
https://physgun.com/dashboard/tickets
https://physgun.com/dashboard/logs

**Comment by robertdrakedennis** [comment]
fixed

also weirdo uses light mode?!
